name: m3t
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - git
  - ninja
  # --- PyTorch + CUDA 12.4 ---
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  # --- Your requested packages ---
  - pandas
  - pyyaml
  - tqdm
  - scipy
  - scikit-image
  - nibabel
  - pillow
  - einops
  - wandb
  - captum
  - simpleitk
  - pip:
      - "monai[all] @ git+https://github.com/Project-MONAI/MONAI.git"