project: Embryo_Edema_Classification
ckpt_dir: checkpoints
out_channels: 64
emb_size: 256
depth: 12
p_cnn3d: 0.10
p_feat: 0.20
p_token: 0.10
p_transformer: 0.10
p_drop_path: 0.10
batch_size: 3
epochs: 1000
lr: 1e-4
save_every: 5
ssl_ckpt: null
