project: SSL_Embryo_M3T_HYBRID
ckpt_dir: checkpoints
mean: 1776.835584
std: 5603.538718
out_channels: 64
emb_size: 256
depth: 12
p_cnn3d: 0.05
p_feat: 0.05
p_token: 0.10
p_transformer: 0.10
p_drop_path: 0.05
mask_ratio: 0.35
lr: 6e-4
batch_size: 12
epochs: 800
warmup_epochs: 10
lambda_recon: 0.5
lambda_contrast: 2.0
lambda_rot: 0.5
lambda_jig: 0.5
weight_decay: 3e-6
save_every: 10
data_list: []
